options:
  san_ip:
    type: string
    description: "Management VIP address of the Pure Storage FlashArray"
  pure_api_token:
    type: string
    description: "API token for FlashArray access"
  protocol:
    type: string
    default: iscsi
    description: "SAN protocol to use. Valid options are iscsi or fc."
